### ISSUE TITLE
Misleading function name

### ISSUE THREAD

**Issue by ecoppen** [Tasnim-Uddin/Programming-challenges#1]
https://github.com/Tasnim-Uddin/Programming-challenges/blob/938eeee90ef0132d2a8e419b5bb2f3012a3bff8f/Brampton%20Manor%20Academy/Challenge%201/Rods%20Converter.py#L1

This function has been named as though it's where you input rods. It can and should be doing this though! 
```
def rodsInput():
    rods=float(input("Input rods: "))
    print("You input",rods,"rods")
    return rods
```
https://github.com/Tasnim-Uddin/Programming-challenges/blob/938eeee90ef0132d2a8e419b5bb2f3012a3bff8f/Brampton%20Manor%20Academy/Challenge%201/Rods%20Converter.py#L24

becomes `rods=rodsInput()`

**Comment by Tasnim-Uddin** [comment]
alright i've done that now, i just didn't know how to make rods global

**Comment by ecoppen** [comment]
No need to make it global, in fact you rarely ever should make anything global! Return the value back to a variable or alternative, then pass it on to the next function/procedure.

**Comment by Tasnim-Uddin** [comment]
I understand now. After I updated my code, should I replace the new code with the old code in the github folder?

**Comment by ecoppen** [comment]
Yes - GitHub will keep your old versions for you, so you can always compare later and see what changed exactly. Once that's done, you can close this issue.

**Comment by Tasnim-Uddin** [comment]
ok i did it
